apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-app-python
  name: service-app-python
  namespace: default
spec:
  ports:
  - name: backend-app-http
    port: 80
    protocol: TCP
    targetPort: backend-port
  selector:
    app: app-python
  type: LoadBalancer